apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-shop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: e-shop
  template:
    metadata:
      labels:
        app: e-shop
    spec:
      containers:
      - name: e-shop
        image: your-docker-registry/e-shop:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.25"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: e-shop-service
spec:
  selector:
    app: e-shop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer